### PR TITLE
wasmprinter: Limit the maximum number of locals

### LINKED ISSUE #52: [crash/fuzzing] Resources exhaustion (CPU/MEM) using wasmprinter::print_bytes()
During fuzzing of `wasmprinter`, I trigger a resources exhaustion bug leading to full CPU usage when parsing a crafted wasm module. The file is only 650 bytes in size.

Download: [huge_cpu_usage_wasmprinter.zip](https://github.com/bytecodealliance/wasm-tools/files/4926087/huge_cpu_usage_wasmprinter.zip)

Repo:
``` rust
use std::env;
use std::fs::File;
use std::io;
use std::io::Read;

/// Read the contents from file path
fn read_contents_from_path(path_str: &String) -> Result<Vec<u8>, io::Error> {
    let mut buffer: Vec<u8> = Vec::new();
    let file_path = std::path::PathBuf::from(path_str);

    println!("file_to_process: {:?}", file_path);

    let mut file = File::open(file_path)?;
    file.read_to_end(&mut buffer)?;
    drop(file);
    Ok(buffer)
}

fn main() {
    println!("Start debugging of wasmprinter_parser");
    let args: Vec<String> = env::args().collect();

    // verify file_to_process is provided
    if args.len() != 2 {
        println!("Usage: wasmprinter_parser <file_to_process>\n");
        return;
    }

    // read data from provided file
    let data = read_contents_from_path(&args[1]).expect("cannot read file content");

    // call the fuzzing target
    wasmprinter::print_bytes(&data).is_ok();

    println!("No crash, everything is OK\n");
}

```

### PR DESCRIPTION
**Pull request by alexcrichton**
Don't inflate a small file to gigabytes of `(local` declarations!

Closes #52

### CODE REVIEW

File: crates/wasmprinter/src/lib.rs [hunk 1]
```diff
@@ -15,6 +15,8 @@ use std::mem;
 use std::path::Path;
 use wasmparser::*;
 
+const MAX_LOCALS: u32 = 50000;
```
Comment (tschneidereit) [inline crates/wasmprinter/src/lib.rs:18]: Are you sure this is enough? While it might seem like it'd obviously be, I vaguely remember some preposterously large functions generated by Emscripten back in the asm.js days. Perhaps toolchains don't do those kinds of things anymore?

Comment (fitzgen) [reply crates/wasmprinter/src/lib.rs:18]: I would copy whatever cranelift / wasmparser already have as their limit.

Comment (fitzgen) [reply crates/wasmprinter/src/lib.rs:18]: Which is also `50000` :laughing:

Comment (tschneidereit) [reply crates/wasmprinter/src/lib.rs:18]: hah, fair enough 😁 I do wish the spec imposed limits here, but oh well.
