### PR TITLE
Encode instance exports properly

### LINKED ISSUE #977: wasm-tools compose creates invalid instances within the composed component
After I run the `wasm-tools compose` [example](https://github.com/bytecodealliance/wasm-tools/tree/main/crates/wasm-compose/example), I cannot run `wasm-tools component wit` on the composed component. I get the following error:

```
Error: failed to decode WIT document

Caused by:
    0: failed to decode WIT from import `streams`
    1: unexpected unnamed type
```

The issue seems to be that the composed component has incorrectly encoded instances. You can see this when looking at one of the instances before and after composition happen. Note: the instance in question is not involved in the composition beyond being a shared dependency of the two components being merged into one composed component:

**Before composition**

```wat
(component
 (type (;0;)
    (instance
      (type (;0;) u32)
      (export (;1;) "wall-clock" (type (eq 0)))
      (type (;2;) (record (field "seconds" u64) (field "nanoseconds" u32)))
      (export (;3;) "datetime" (type (eq 2)))
      (type (;4;) (func (param "this" 1) (result 3))) ;; NOTE: the result points to the "datetime" export
      (export (;0;) "now" (func (type 4)))
    )
  )
;; ...
```

**After composition**

```wat
(component
  (type (;0;)
    (instance
      (type (;0;) u32)
      (export (;1;) "wall-clock" (type (eq 0)))
      (type (;2;) (record (field "seconds" u64) (field "nanoseconds" u32)))
      (export (;3;) "datetime" (type (eq 2)))
      (type (;4;) (func (param "this" 0) (result 2))) ;; NOTE: the result type points directly to the record
      (export (;0;) "now" (func (type 4)))
    )
  )
;; ...
```

At some point this instance seems to have one of its functions changed so that its result type points directly to a record field (which is illegal) instead of pointing to a type.

@alexcrichton noted the following [on Zulip](https://bytecodealliance.zulipchat.com/#narrow/stream/206238-general/topic/wasm-tools.20compose.20example/near/348479284):

> I suspect that this may be an issue with both the decoder and encoder perhaps? The constructs used here were added after the initial implementation of wasm-compose so it hasn't been updated to use exports in the same way. The decoder probably needs an update to read the structure of use-the-exported-item and the encoder needs to be updated to use items as they're exported. Shouldn't be too hard ideally as wit-component deals with similar problems as well, but if you'd like I think opening an issue for this would be good

### PR DESCRIPTION
**Pull request by rylev**
Fixes #977 

Instance exports were not being reflected in the TypeMap meaning that future declarations would refer to the direct type definition instead of the export definition. This updates that handling so that the type map is updated with the index of the export. 

Big thanks to @peterhuene for the helpful hints!

> *Note*: I also updated some error handling to give better errors to help with a new error I'm seeing. Let me know if you'd rather I separate that out into a new PR.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Would it be easy enough to add a test for this as well?

File: crates/wasm-compose/src/encoding.rs [hunk 1]
```diff
@@ -143,8 +143,11 @@ impl<'a> TypeEncoder<'a> {
         }
 
         for (name, url, ty) in exports {
-            let ty = self.component_entity_type(&mut encoded, &mut types, ty);
-            encoded.export(name, url, ty);
+            let type_definiton = self.0.type_from_id(ty.id().unwrap()).unwrap();
+            let export = self.component_entity_type(&mut encoded, &mut types, ty);
+            // Point the type index to the export instead of the concrete type definition
+            types.insert(PtrKey(type_definiton), encoded.type_count());
+            encoded.export(name, url, export);
```
Comment (peterhuene) [inline crates/wasm-compose/src/encoding.rs:150]: The test failure is because we only want to do this map update when the item being exported is a type, so that the type map points at the exported (i.e. "named") index rather than the original type definition index.

To do that, I think something like this would work (here and the other places we needed this change):

```suggestion
            let id = match &ty {
                ComponentEntityType::Type { created: id, .. } => Some(*id),
                _ => None,
            };

            let ty = self.component_entity_type(&mut encoded, &mut types, ty);
            if let Some(id) = id {
                let ty = self.0.type_from_id(id).unwrap();
                types.insert(PtrKey(ty), encoded.type_count());
            }

            encoded.export(name, url, ty);
```

File: crates/wasmparser/src/validator/types.rs [hunk 2]
```diff
@@ -816,6 +816,20 @@ impl ComponentEntityType {
             Self::Value(ty) => ty.type_size(),
         }
     }
+
+    /// The underlying `TypeId` for this entity type if one exists
+    pub fn id(&self) -> Option<TypeId> {
```
Comment (peterhuene) [inline crates/wasmparser/src/validator/types.rs:821]: I think we can remove this function if we stick to something from the above suggestion.

File: crates/wasm-compose/tests/compose.rs [hunk 3]
```diff
@@ -75,6 +75,13 @@ fn component_composing() -> Result<()> {
                 )
             })?;
 
+            wit_component::decode("component", &bytes).with_context(|| {
+                format!(
+                    "failed to decode component bytes as a wit component `{}`",
```
Comment (peterhuene) [inline crates/wasm-compose/tests/compose.rs:80]: Nit: 

```suggestion
                    "failed to decode WIT from component bytes for test cast `{}`",
```

**Review by peterhuene — APPROVED** [review]
Looks great, thanks for fixing this!

Just the one minor nit and I think this is good to merge.

**Comment by peterhuene** [comment]
Thanks @rylev!
