### PR TITLE
Add a few doc comments around validation, and fix some typos.

### LINKED ISSUE #2063: Tolerate duplicate imports when creating components
Multiple imports of the same name are in-spec for core-wasm modules but [not allowed for components](https://github.com/WebAssembly/component-model/blob/main/design/mvp/Explainer.md#import-and-export-definitions). Currently, attempting to componentize a module with non-uniquely named imports yields…

```
% wasm-tools component new main-with-dupe-imports.wasm -o component-with-dupes.wasm --adapt wasi_snapshot_preview1.wasm
error: failed to encode a component from module

Caused by:
    0: failed to decode world from module
    1: module was not valid
    2: module has duplicate import for `wasi_snapshot_preview1::fd_write`
```

We should pick a unique import of each name and ignore the rest when componentizing. Since inter-component linking is done solely by name, multiple same-named imports have no way of being distinguished in order to be satisfied individually—even if they had unique types, for example—and so nothing is lost by ignoring them.

### PR DESCRIPTION
**Pull request by erikrose**
Breaking these free of an old attempt to fix #2063.

### CODE REVIEW

File: crates/wasmparser/src/validator.rs [hunk 1]
```diff
@@ -346,7 +346,7 @@ pub enum ValidPayload<'a> {
     /// This result indicates that the specified parser should be used instead
     /// of the currently-used parser until this returned one ends.
     Parser(Parser),
-    /// A function was found to be validate.
+    /// A function was found to be valid.
```
Comment (alexcrichton) [inline crates/wasmparser/src/validator.rs:349]: Oh "validate" here should have been "validated", the function isn't valid yet in this variant and it still needs to be validated.

**Review by alexcrichton — APPROVED** [review]

File: crates/wasmparser/src/validator.rs (hunk 1 above)
Comment (erikrose) [reply crates/wasmparser/src/validator.rs]: Fixed and push -f'd!
