### PR TITLE
fix: Enhance how Instance::* variants are printed

### LINKED ISSUE #547: `wasmprinter`: improve formatting of instantiation from exports
From bytecodealliance/wit-bindgen#183, `wasmprinter` currently prints this for instaniation from exports:

```wat
(instance (;3;) core (export "$imports" (table 0)) (export "a" (func 16)) (export "b" (func 17)) (export "c" (func 18)) (export "d" (func 19)) (export "e" (func 20)) (export "f" (func 21)) (export "g" (func 22)) (export "h" (func 23)) (export "i" (func 24)) (export "j" (func 25)) (export "k" (func 26)) (export "l" (func 27)) (export "m" (func 28)) (export "n" (func 29)) (export "o" (func 30)) (export "p" (func 31)))
```

This would be better formatted as:

```wat
(instance (;3;) core
  (export "$imports" (table 0))
  (export "a" (func 16))
  (export "b" (func 17))
  (export "c" (func 18))
  (export "d" (func 19))
  (export "e" (func 20))
  (export "f" (func 21))
  (export "g" (func 22))
  (export "h" (func 23))
  (export "i" (func 24))
  (export "j" (func 25))
  (export "k" (func 26))
  (export "l" (func 27))
  (export "m" (func 28))
  (export "n" (func 29))
  (export "o" (func 30))
  (export "p" (func 31))
)
```

### PR DESCRIPTION
**Pull request by saulecabrera**
Fixes #547 

This commit replaces spaces for newlines when printing each of the
Instance::* variants.

---
Some notes:

- I'm assuming `wasmprinter` doesn't have any unit tests for components, given that wast doesn't support components yet. 
- Aside from adding support for instantiation from exports, I've added also formatting for the other `Instance` variants. Running wasm-tools on the [examples in `wit-bindgen`](https://github.com/bytecodealliance/wit-bindgen/tree/main/crates/wit-component/tests/components/imports) gives the following:

```wat
;; 1
(instance (;6;) core
  (export "foo1" (func 11))
  (export "foo2" (func 12))
  (export "foo3" (func 13))
)

;; 2 
(instance (;7;) (instantiate (module 0)
    (with "bar" (instance 4))
    (with "baz" (instance 5))
    (with "foo" (instance 6))
  )
)

;; 3
(instance (;2;)
  (export "a" (func 11))
  (export "b" (func 12))
  (export "c" (func 13))
)

```

Open question/thought:

- Is there a preference to print 2 in the snippet above (`Instance::Module`), like this instead:
```wat
(instance (;7;) (instantiate (module 0)
  (with "bar" (instance 4))
  (with "baz" (instance 5))
  (with "foo" (instance 6))
))
```

cc/ @peterhuene

### CODE REVIEW

**Review by peterhuene — APPROVED** [review]
That's correct, the in-repo tests are waiting on `wat` updating, so this is a little ad hoc for now.

Thanks for fixing this. We'll need to update the baselines in `wit-bindgen` after we merge this.

File: crates/wasmprinter/src/lib.rs [hunk 1]
```diff
@@ -2882,7 +2882,7 @@ impl Printer {
                     self.print_idx(&state.module_names, index)?;
                     self.end_group();
                     for arg in args.iter() {
-                        self.result.push(' ');
+                        self.newline();
```
Comment (peterhuene) [inline crates/wasmprinter/src/lib.rs:2885]: I wonder if we should also do a `self.newline()`above that separates the `instance` group with the `instantiate` group (both here and for `instantiate component` below).

That would turn:

```wat
(instance (;7;) (instantiate (module 0)
    (with "bar" (instance 4))
    (with "baz" (instance 5))
    (with "foo" (instance 6))
  )
)
```

into

```wat
(instance (;7;)
  (instantiate (module 0)
    (with "bar" (instance 4))
    (with "baz" (instance 5))
    (with "foo" (instance 6))
  )
)
```

What are your thoughts?

Comment (peterhuene) [reply crates/wasmprinter/src/lib.rs:2885]: Although that would mean an instantiation with arguments spans multiple lines.

Let's leave it as you have now, can always address later.

**Comment by saulecabrera** [comment]
> We'll need to update the baselines in wit-bindgen after we merge this.

Makes sense, I'll go ahead update the tests once this is merged!
